### PR TITLE
apk download option added in landing page

### PR DESCRIPTION
**Pull request by Subhabrata20**
odisha local apk download from landing page.

### CODE REVIEW

**Review by ditikrushna — CHANGES_REQUESTED** [review]
Please add an updated APK.

**Review by ditikrushna — CHANGES_REQUESTED** [review]
Add download attribute in the anchor tag. 

Add this one :- `<a href="apk/odisha-local.apk" download>`

**Comment by Subhabrata20** [comment]
you will check it fast. already i done .

**Comment by ditikrushna** [comment]
Sorry, I'm not getting your point. You are making a pull request which is not correct. I suggested you add that code.  Why you are not doing it? I don't have access to modify this pull request as you are the owner of this pull request.

**Comment by Subhabrata20** [comment]
sorry, actually I did not understand your suggestion. now I fixed the bug and push the code

**Comment by ditikrushna** [comment]
That's fine ;)

**Pull request merged**
